name: 'Clang Format Check'

on:
  workflow_call:
    secrets:
      caller_token:
        required: true

# Force bash to apply pipefail option so pipeline failures aren't masked
defaults:
  run:
    shell: bash

jobs:
  skip-duplicate-actions:
    uses: NathanaelGandhi/clang-format-check-reusable-workflow/.github/workflows/duplicate-actions-check-reusable.yaml@main
  format-check:
    name: Format check
    #Continue if check-for-duplicates found no duplicates. Always runs for pull-requests.
    needs: skip-duplicate-actions
    if: ${{ needs.skip-duplicate-actions.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: ubuntu:latest
    steps:
      - name: Install format checker & dependencies
        run: |
          apt-get update && apt-get install -y clang-format git
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: repo
      - name: Generate format differences
        run: |
          cd repo
          # find .c and .h files and apply style .clang-format files within those directories and their subdirectories
          find . -type d -name .clang-format -execdir sh -c 'clang-format -i -style=file "$0"/*.c "$0"/*.h' {} \;
          # find .c and .h files and apply style .clang-format file in the same directory or in one of the parent directories.
          #find . -name "*.[ch]" -exec clang-format -i -style=file {} +
          git diff > $GITHUB_WORKSPACE/style_differences.txt
      - name: Archive Static Analysis Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: style_differences
          path: style_differences.txt
      - name: Error on differences
        run: |
          if [[ -s style_differences.txt ]];
          then
            cat style_differences.txt
            exit -1
          fi
